src/java/MB/ClienteMB.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MB;

import java.util.ArrayList;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import modelo.Cliente;
import modelo.Pedido;
import service.ClienteDados;

@ManagedBean
@SessionScoped
public class ClienteMB {
    private ClienteDados clientinfo = new ClienteDados();
    private Cliente client = new Cliente();
    private Cliente selectedclient;
    
    public void addcliente(){
        clientinfo.addcliente(client);
        client = new Cliente();
    }

    public ClienteDados getClientinfo() {
        return clientinfo;
    }

    public void setClientinfo(ClienteDados clientinfo) {
        this.clientinfo = clientinfo;
    }

    public Cliente getClient() {
        return client;
    }

    public void setClient(Cliente client) {
        this.client = client;
    }


    public ArrayList<Cliente> getListaClientes(){
        return clientinfo.getListaCliente();
    }
    public String vaiPedido(){
        System.out.println("MB.ClienteMB.vaiPedido()");
        return "CadastroPedido";
    }

    public Cliente getSelectedclient() {
        return selectedclient;
    }

    public void setSelectedclient(Cliente selectedclient) {
        this.selectedclient = selectedclient;
    }
    
}

src/java/MB/PedidoMB.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MB;

import java.util.ArrayList;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import modelo.Cliente;
import modelo.ItemPedido;
import modelo.Pedido;
import modelo.Produto;
import service.PedidoDados;

/**
 *
 * @author 150499
 */
@ManagedBean
@SessionScoped
public class PedidoMB {
    private PedidoDados listaPedidos = new PedidoDados();
    private Pedido x = new Pedido();
    private ItemPedido item = new ItemPedido();
    private Cliente seleclient;
    
    public void addItem(){
        x.addItem(item);
        item = new ItemPedido();
    }
   
    public void addPedido(){
        x.setCliente(seleclient);
        listaPedidos.addpedido(x);
        x = new Pedido();
    }

    public ArrayList<Pedido> getListaPedidos() {
        return listaPedidos.getListaPedidos();
    }

    public void setListaPedidos(PedidoDados listaPedidos) {
        this.listaPedidos = listaPedidos;
    }

    public Pedido getX() {
        return x;
    }

    public void setX(Pedido x) {
        this.x = x;
    }

    public ItemPedido getPed() {
        return item;
    }
    public ArrayList<ItemPedido> getListaItens(){
        return x.getItens();
    }
    
    public Cliente getSeleclient() {
        return seleclient;
    }

    public void setSeleclient(Cliente seleclient) {
        this.seleclient = seleclient;
    }
    
}

src/java/MB/ProdutoMB.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MB;

import java.util.ArrayList;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import modelo.Produto;
import service.ProdutoDados;



@ManagedBean
@SessionScoped
public class ProdutoMB {
    private ProdutoDados listaProduto = new ProdutoDados();
    private Produto prod = new Produto();
    private Produto selectedprod;
    public void salvax(){
        listaProduto.add(prod);
        prod = new Produto();
    }
    
    public ArrayList<Produto> getListaProduto(){
        return listaProduto.getProdutos();
    }
    public Produto getProd(){
        return prod;
    }
    public void setProd(Produto prod){
        this.prod = prod;
    }

    public Produto getSelectedprod() {
        return selectedprod;
    }

    public void setSelectedprod(Produto selectedprod) {
        this.selectedprod = selectedprod;
    }
    
}

web/CadastroCliente.xhtml
<ui:composition template="template.xhtml"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:p="http://primefaces.org/ui">

    <ui:define name="title">
        <h:outputText value="Cadastro de Funcionários" />
    </ui:define>
    <ui:define name="principal">
        <h:form id="formcliente">
            <p:panelGrid columns="2">
                <p:outputLabel value="Endereço"/>
                <p:inputText value="#{clienteMB.client.endereco}" />
                <p:outputLabel value="Limite"/>
                <p:inputText value="#{clienteMB.client.limite}" />
                <p:outputLabel value="Nome"/>
                <p:inputText value="#{clienteMB.client.nome}" />
                <p:outputLabel value="Status"/>
                <p:inputText value="#{clienteMB.client.status}" />
                <p:outputLabel value="Telefone"/>
                <p:inputText value="#{clienteMB.client.telefone}" />
            </p:panelGrid>
            <p:commandButton value="Registrar" action="#{clienteMB.addcliente()}" update=":formcliente" />
            <p:commandButton value="Fazer Pedido" action="#{clienteMB.vaiPedido()}" update=":formcliente" />
            <p:dataTable id="dataTableCliente"
                         var="f" value="#{clienteMB.listaClientes}"
                         rows="10"
                         paginator="true"
                         paginatorTemplate="{CurrentPageReport} {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
                         rowsPerPageTemplate="5,10,15"
                         selectionMode="single" selection="#{clienteMB.selectedclient}" rowKey="#{f.codigo}"
                         >
                <p:column headerText="Codigo">
                    <p:outputLabel value="#{f.codigo}"/>
                </p:column>
                <p:column headerText="Cliente">
                    <p:outputLabel value="#{f.nome}"/>
                </p:column>
                <p:column headerText="Endereço">
                    <p:outputLabel value="#{f.endereco}"/>
                </p:column>
                <p:column headerText="Limite">
                    <p:outputLabel value="#{f.limite}"/>
                </p:column>
                <p:column headerText="Telefone">
                    <p:outputLabel value="#{f.telefone}"/>
                </p:column>
                
            </p:dataTable>
            
        </h:form>
    </ui:define>
</ui:composition>

web/CadastroPedido.xhtml
<ui:composition template="template.xhtml"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:p="http://primefaces.org/ui">

    <ui:define name="title">
        <h:outputText value="#{clienteMB.selectedclient.nome}" />
    </ui:define>
    <ui:define name="principal">
        <h:form id="formpedido">
            <p:panelGrid columns="2">
                <p:outputLabel value="Produto" />
                <p:selectOneMenu value="#{pedidoMB.ped.produto}" converter="converterProduto" style="width:100%">
                    <f:selectItems value="#{produtoMB.listaProduto}" var="aux"
                                   itemValue="#{aux}" itemLabel="#{aux.nome}" />
                </p:selectOneMenu>
                <p:outputLabel value="Quantidade"/>
                <p:inputText value="#{pedidoMB.ped.quantidade}" />
            </p:panelGrid>
            <p:commandButton value="Add Item" action="#{pedidoMB.addItem()}" update=":formpedido" />
            <p:commandButton value="Add Pedido" action="#{pedidoMB.addPedido()}" update=":formpedido" />
            <p:dataTable id="dataTableItem"
                         var="g" value="#{pedidoMB.listaItens}"
                         rows="10"
                         paginator="true"
                         paginatorTemplate="{CurrentPageReport} {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
                         rowsPerPageTemplate="5,10,15"
                         
                         >
                <p:column headerText="IDPedido">
                    <p:outputLabel value="#{g.numero}"/>
                </p:column>
                <p:column headerText="IDProduto">
                    <p:outputLabel value="#{g.produto.codigo}"/>
                </p:column>
                <p:column headerText="Produto">
                    <p:outputLabel value="#{g.produto.nome}"/>
                </p:column>
                <p:column headerText="Quantidade">
                    <p:outputLabel value="#{g.quantidade}"/>
                </p:column>
            </p:dataTable>
            <p:panelGrid columns="2">
                
                <p:outputLabel value="Cliente" />
                <p:selectOneMenu value="#{pedidoMB.seleclient}" converter="converterCliente" style="width:100%">
                    <f:selectItems value="#{clienteMB.listaClientes}" var="aux"
                                   itemValue="#{aux}" itemLabel="#{aux.nome}" />
                </p:selectOneMenu>
            </p:panelGrid>
            <p:dataTable id="dataTablePedido"
                         var="f" value="#{pedidoMB.listaPedidos}"
                         rows="10"
                         paginator="true"
                         paginatorTemplate="{CurrentPageReport} {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
                         rowsPerPageTemplate="5,10,15"
                         
                         >
                <p:column headerText="Cod">
                    <p:outputLabel value="#{f.numero}"/>
                </p:column>
                <p:column headerText="Cliente">
                    <p:outputLabel value="#{f.cliente.nome}"/>
                </p:column>
            </p:dataTable>
            
            
            
        </h:form>
    </ui:define>
</ui:composition>

web/CadastroProduto.xhtml
<ui:composition template="template.xhtml"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:p="http://primefaces.org/ui">

    <ui:define name="title">
        <h:outputText value="Cadastro de Produtos" />
    </ui:define>
    <ui:define name="principal">
        <h:form id="formprod">
            <p:panelGrid columns="2">
                <p:outputLabel value="Nome"/>
                <p:inputText value="#{produtoMB.prod.nome}" />
                <p:outputLabel value="Preco"/>
                <p:inputText value="#{produtoMB.prod.preco}" />
                <p:outputLabel value="Imposto"/>
                <p:inputText value="#{produtoMB.prod.imposto}" />
                <p:outputLabel value="Moeda"/>
                <p:inputText value="#{produtoMB.prod.moeda}" />
            </p:panelGrid>
            <p:commandButton value="Registrar" action="#{produtoMB.salvax()}" update=":formprod" />
            <p:dataTable id="dataTableProduto"
                         var="f" value="#{produtoMB.listaProduto}"
                         rows="10"
                         paginator="true"
                         paginatorTemplate="{CurrentPageReport} {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
                         rowsPerPageTemplate="5,10,15"
                         
                         >
                <p:column headerText="Id">
                    <p:outputLabel value="#{f.codigo}"/>
                </p:column>
                <p:column headerText="Produto">
                    <p:outputLabel value="#{f.nome}"/>
                </p:column>
                <p:column headerText="Preco">
                    <p:outputLabel value="#{f.imposto}"/>
                </p:column>
                <p:column headerText="Imposto">
                    <p:outputLabel value="#{f.imposto}"/>
                </p:column>
                <p:column headerText="Moeda">
                    <p:outputLabel value="#{f.moeda}"/>
                </p:column>
                
            </p:dataTable>
        </h:form>
    </ui:define>
</ui:composition>

web/Teste.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        Hello from Facelets
        Hello from FaceletsHello from Facelets
        Hello from Facelets
        Hello from Facelets
        
        
    </h:body>
</html>

web/funcionario.xhtml
<ui:composition template="template.xhtml"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:p="http://primefaces.org/ui">

    <ui:define name="title">
        <h:outputText value="Cadastro de Funcionários" />
    </ui:define>

    <ui:define name="principal">
        <h1>Cadastro Funcionários</h1>
        <h:form id="formFunc">
            <p:panelGrid columns="2">
                <p:outputLabel value="Matricula:"/>
                <p:inputText   value="#{funcionarioMB.func.matricula}"/>
                <p:outputLabel value="Nome:"/>
                <p:inputText   value="#{funcionarioMB.func.nome}"/>

                <p:outputLabel value="Empresa" />
                <p:selectOneMenu value="#{funcionarioMB.empresaEscolhida}" converter="converterEmpresa" style="width:100%">
                    <f:selectItems value="#{funcionarioMB.empresas}" var="aux"
                                   itemValue="#{aux}" itemLabel="#{aux.nome}" />
                </p:selectOneMenu>


                <p:outputLabel value="Função:"/>
                <p:inputText   value="#{funcionarioMB.func.funcao}"/>
                <p:outputLabel value="Salário:"/>
                <p:inputText   value="#{funcionarioMB.func.salario}"/>
            </p:panelGrid>
            <p:commandButton value="Salvar"
                             action="#{funcionarioMB.salvar()}" 
                             update=":formFunc" />

            <p:growl id="msgs" showDetail="true"/>
            <p:dataTable id="dataTableFunc"
                         var="f" value="#{funcionarioMB.funcionarios}"
                         rows="10"
                         paginator="true"
                         paginatorTemplate="{CurrentPageReport} {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
                         rowsPerPageTemplate="5,10,15"
                         editable="true"
                         selection="#{funcionarioMB.selectedFunc}"
                         selectionMode="single"
                         rowKey="#{f.matricula}"
                         >



                <p:ajax event="rowEdit" listener="#{funcionarioMB.onRowEdit}" update=":formFunc:msgs" />

                <p:column headerText="Matricula">
                    <p:outputLabel value="#{f.matricula}"/>
                </p:column>
                <p:column headerText="Nome" filterBy="#{f.nome}" 
                          filterMatchMode="contains" >
                    <p:outputLabel value="#{f.nome}"/>
                </p:column>
                <p:column headerText="Função">
                    <p:cellEditor>
                        <f:facet name="output"><p:outputLabel value="#{f.funcao}" /></f:facet>
                        <f:facet name="input"><p:inputText value="#{f.funcao}" style="width:100%" label="Função"/></f:facet>
                    </p:cellEditor>
                </p:column>
                <p:column headerText="Salário">
                    <p:outputLabel value="#{f.salario}"/>
                </p:column>

                <p:column headerText="Empresa" >
                    <p:cellEditor>
                        <f:facet name="output"> <p:outputLabel value="#{f.empresa.nome}"/></f:facet>
                        <f:facet name="input" >
                            <p:selectOneMenu value="#{f.empresa}" converter="converterEmpresa" style="width:100%">
                             <f:selectItems value="#{funcionarioMB.empresas}" var="aux"
                                               itemValue="#{aux}" itemLabel="#{aux.nome}"
                                               />
                            </p:selectOneMenu>
                        </f:facet>
                    </p:cellEditor>
                </p:column>

                <p:column style="width:32px">
                    <p:rowEditor />
                </p:column>
                <p:column style="width:32px">
                    <p:commandLink styleClass="ui-icon ui-icon-trash" 
                                   actionListener="#{funcionarioMB.removeFuncionario(f)}"
                                   update="dataTableFunc"
                                   />
                </p:column>

            </p:dataTable>

            <p:contextMenu for="dataTableFunc">
                <p:menuitem value="Remove" 
                            update="dataTableFunc" 
                            icon="ui-icon-close" 
                            actionListener="#{funcionarioMB.removeSelected}"/>
            </p:contextMenu>




        </h:form>


    </ui:define>
</ui:composition>

web/index.xhtml
<ui:composition template="template.xhtml"
               xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui">
                
        <ui:define name="title">
		<h:outputText value="Início" />
	</ui:define>

	<ui:define name="principal">
			<h1>Início</h1>
	</ui:define>
</ui:composition>

web/menu.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:p="http://primefaces.org/ui">
	<h:form>
	<p:menubar>
		<p:submenu label="Cadastro">
			<p:submenu label="Produto">
				<p:menuitem value="Cadastro de Clientes" url="/faces/CadastroCliente.xhtml" ></p:menuitem>
				<p:menuitem value="Cadastro de Produtos"   url="/faces/CadastroProduto.xhtml"></p:menuitem>
                                <p:menuitem value="Cadastro de Pedidos"   url="/faces/CadastroPedido.xhtml"></p:menuitem>
				<p:menuitem value="Tela2"   url="/faces/tela2.xhtml"></p:menuitem>
                                <p:menuitem value="Teste"   url="/faces/Teste.xhtml"></p:menuitem>
			</p:submenu>
			<p:menuitem value="Menu2"></p:menuitem>
			<p:separator/>
			<p:menuitem value="Menu3"></p:menuitem>
		</p:submenu>
		<p:submenu label="Help">
			<p:menuitem value="About JournalDev"></p:menuitem>
			<p:menuitem value="Contact Us"></p:menuitem>
			<p:separator/>
			<p:menuitem value="Help"></p:menuitem>
		</p:submenu>
	</p:menubar>
</h:form>
</ui:composition>

web/rodape.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui">
                <p:outputLabel value="Sistema 2.0" />
</ui:composition>

web/tela1.xhtml
<ui:composition template="template.xhtml"
               xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui">
                
        <ui:define name="title">
		<h:outputText value="Tela1" />
	</ui:define>

	<ui:define name="principal">
			<h1>Tela1</h1>
	</ui:define>
</ui:composition>

web/tela2.xhtml
<ui:composition template="template.xhtml"
               xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui">
                
        <ui:define name="title">
		<h:outputText value="Tela2" />
	</ui:define>

	<ui:define name="principal">
			<h1>Tela2</h1>
	</ui:define>
</ui:composition>

web/template.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      >
<f:view>
	<h:head>
		<style> .ui-datagrid-no-border .ui-datagrid-content { border: none; } </style>

		<title>
		   <ui:insert name="title">
				<h:outputLabel value="Sistema" />
		   </ui:insert>
	    </title>
	    <style>
	     .ui-layout-north {
        z-index:20 !important;
        overflow:visible !important;
    }

    .ui-layout-north .ui-layout-unit-content {
        overflow:visible !important;
    }
	    </style>
	    
	</h:head>

	<h:body>
		<p:layout id="globalLayout" fullPage="true" >

			<p:layoutUnit position="north">
				<ui:include src="/menu.xhtml" />
			</p:layoutUnit>
			
			<p:layoutUnit position="center">
				<ui:insert name="principal" />
			</p:layoutUnit>
			
			<p:layoutUnit position="south">
				<ui:include src="rodape.xhtml" />
			</p:layoutUnit>
		</p:layout>

	</h:body>
</f:view>
</html>